### ISSUE TITLE
F-Droid build failed. 

### ISSUE THREAD

**Issue by linsui** [forkgram/TelegramAndroid#221]
```
ERROR: Could not build app org.forkgram.messenger: Unexpected version/version code in output; APK: '10.5.0.0' / '422807',  Expected: '10.5.0.1' / '422817'
```

Could you please update the version name and code?

**Comment by 23rd** [comment]
Sorry, I’m not sure what should I change.
As far as I remember the first five digits from my version code should be taken + should be added the magic digit `8`.
So, the current latest version is `422819`. The first five digits are `42281`. With the magic digit result will be: `422818`.

**Comment by linsui** [comment]
I don't know why the apk built by F-Droid has an old version name.

**Comment by ghgabr** [comment]
I'm not really an Android developer, but it seems very likely that the check fails because the version was **not** really changed anywhere in the code..!

See https://github.com/forkgram/TelegramAndroid/compare/10.5.0.0..forkgram:TelegramAndroid:10.5.0.1?diff=unified&w= , these are all the differences between the 10.5.0.0 version and this last one.  
No version change.

After quite a bit of effort I saw that the only thing changed in the last version was indeed the *omission* of the 968f10722 commit.

**Comment by ghgabr** [comment]
Ok there was obviously also at least the patch "*Fixed forward date from users with privacy.*" modified, from the 68d20a55f in the 10.5.0.0 version to the 57f667c49 of the 10.5.0.1.

This is extremely confusing

**Comment by ghgabr** [comment]
(ok it looks like those were the only things changed)

**Comment by 23rd** [comment]
@linsui please, can I ask you to change `subdir: TMessagesProj_AppFork` with `subdir: TMessagesProj_App` in the metadata yml file from the fdroid repository?

**Comment by linsui** [comment]
Done.
