### ISSUE TITLE
88 mb ?

### ISSUE THREAD

**Issue by iJahangard** [forkgram/TelegramAndroid#50]
Almost have nothing
And it have f*cking 88mb size ? I don't understand

**Comment by RememberTheAir** [comment]
Wow so salty. The distributed apk is this fat probably because it is compiled for every cpu architecture

**Comment by justfortelegram** [comment]
Didn't want to answer to this 10 days ago, but ok.

First of all do not listen to remember the air because he is salty and his suggestions usually retarded as fuck, we all know where this guy came from and how he usually acts in telegram's infrastructure repos.

> Almost have nothing

At least this fork does not contain useless and shitty fixes and doesn't have child in maintainer role and all fixes were done almost perfectly and respectful (why almost? Because there are many ways to implement some of implemented things without changing basic UI), while nekox catogram and other childish forks were implemented in the shitty ways and maintainers are brainless and will remain as brainless, just look up at their development background if you do not trust me.

About size, it is big because, first of all back then it was the official way to create reproducible builds, build type called AFat, which basically stays for a fat version which contains non stripped, non optimized shared libs and code.
Otherwise you wouldn't be able to download and install apk on all possible platforms, again, look at distribution way of nekox and other pointless forks, do not judge without knowledge as remember the air does all the time.
Also he explained why he usually releases debug versions, use search next time


23rd, you shouldn't include debug versions of libs in final the apk files.

**Comment by 23rd** [comment]
The distributed apk file has such size because it is compiled as the Debug version.
The reasons for this decision I described here 
https://github.com/Forkgram/TelegramAndroid/issues/46#issuecomment-751280397.

I'm not forcing anyone to use my fork, there are many other great solutions.
If you have any improvements, I am always open to considering them.
